BaseConfig:
  - interfaceName: can1
    dbcFileName: /home/maximilian/Git/CanGen/dbc/CAN7_UASA2209_Accu_2.dbc
    customWaveFile: /home/maximilian/Git/CanGen/config/Wave/can1.yaml
  #- interfaceName: can0
  #  dbcFileName: /home/maximilian/Git/CanGen/dbc/CAN4_Accu_1.dbc
  #  customWaveFile: /home/maximilian/Git/CanGen/config/Wave/can0.yaml
  
